package board

import (
	"crypto/sha256"
	"flag"
	"fmt"
	"math/rand/v2"
	"os"
	"strings"
	"testing"
	"unicode/utf8"
)

// TestCorporaArePinned holds the BenchmarkBar corpora to the bytes they had
// before the builders moved here, so those rows stay comparable across runs.
func TestCorporaArePinned(t *testing.T) {
	fixed := func() *rand.Rand { return rand.New(rand.NewPCG(0xCA5E1, 0xA12E9A)) }
	for _, c := range []struct{ name, text, want string }{
		{"logs", Logs(fixed(), 1<<20), "5da84e0ea3e187047335a81cfb94228b2b091541c004da37996763a5193b38e8"},
		{"prose", Prose(fixed(), 1<<20), "c7270c76c933f8105430a0694369de23e0634d7a8ffdc6c446ca770991efce4d"},
		{"code", Code(fixed(), 256<<10), "7a289c7bedb1b64435ea4ea97333f30bc8804a6f7b3ebcdc9ee880f33884cd49"},
		{"russian", Russian(fixed(), 1<<20), "14331eddad6a58cf93a49ac59fcc3ed103237fb2327378e082075e8932e2a8af"},
	} {
		if got := fmt.Sprintf("%x", sha256.Sum256([]byte(c.text))); got != c.want {
			t.Errorf("%s corpus sha256 = %s, want %s", c.name, got, c.want)
		}
	}
}

var update = flag.Bool("update", false, "rewrite cells.txt from the generator")

// TestPinnedBoard builds every cell, checks it against its spec, and compares
// the cells with cells.txt. A change to the generator, Seed, or the real text
// shows up as a diff of cells.txt; regenerate it with -update.
func TestPinnedBoard(t *testing.T) {
	var pinned strings.Builder
	fmt.Fprintf(&pinned, "# BenchmarkBoard cells: name, tier, and sha256 of patterns and haystack.\n")
	fmt.Fprintf(&pinned, "# Generated by go test -run TestPinnedBoard -update.\nseed=%#x\n", Seed)
	for _, s := range Cells() {
		c := s.Build()
		ascii := 0
		for _, p := range c.Patterns {
			if len(p) < s.LenLo || len(p) > s.LenHi || !utf8.ValidString(p) {
				t.Fatalf("%s: pattern %q breaks the spec", s.Name(), p)
			}
			if isASCII(p) {
				ascii++
			}
		}
		if s.NonASCII == 0 && ascii != len(c.Patterns) || s.NonASCII == 100 && ascii != 0 {
			t.Fatalf("%s: %d of %d patterns are ASCII", s.Name(), ascii, len(c.Patterns))
		}
		if len(c.Patterns) != s.Count || !utf8.ValidString(c.Haystack) || len(c.Haystack) < s.Size-utf8.UTFMax || len(c.Haystack) > 3*s.Size {
			t.Fatalf("%s: %d patterns, %d haystack bytes", s.Name(), len(c.Patterns), len(c.Haystack))
		}
		if hits := Matches(c.Haystack, c.Patterns, s.Sensitive); (len(hits) == 0) != (s.Spacing == 0) {
			t.Errorf("%s: %d matches with spacing %d", s.Name(), len(hits), s.Spacing)
		}
		tier := "utf8"
		if c.ASCII {
			tier = "ascii"
		}
		fmt.Fprintf(&pinned, "%s %s %s\n", s.Name(), tier, c.Digest())
	}
	if *update {
		if err := os.WriteFile("cells.txt", []byte(pinned.String()), 0o644); err != nil {
			t.Fatal(err)
		}
	}
	if want, err := os.ReadFile("cells.txt"); err != nil || string(want) != pinned.String() {
		t.Fatalf("the generator no longer builds the cells in cells.txt (%v); review, then rerun with -update", err)
	}
}
