package board

import (
	"crypto/sha256"
	"flag"
	"fmt"
	"math/rand/v2"
	"os"
	"slices"
	"strings"
	"testing"
	"unicode/utf8"
)

// TestCorporaArePinned holds the BenchmarkBar corpora to the bytes they had
// before the builders moved here, so those rows stay comparable across runs.
func TestCorporaArePinned(t *testing.T) {
	fixed := func() *rand.Rand { return rand.New(rand.NewPCG(0xCA5E1, 0xA12E9A)) }
	for _, c := range []struct{ name, text, want string }{
		{"logs", Logs(fixed(), 1<<20), "5da84e0ea3e187047335a81cfb94228b2b091541c004da37996763a5193b38e8"},
		{"prose", Prose(fixed(), 1<<20), "c7270c76c933f8105430a0694369de23e0634d7a8ffdc6c446ca770991efce4d"},
		{"code", Code(fixed(), 256<<10), "7a289c7bedb1b64435ea4ea97333f30bc8804a6f7b3ebcdc9ee880f33884cd49"},
		{"russian", Russian(fixed(), 1<<20), "14331eddad6a58cf93a49ac59fcc3ed103237fb2327378e082075e8932e2a8af"},
	} {
		if got := fmt.Sprintf("%x", sha256.Sum256([]byte(c.text))); got != c.want {
			t.Errorf("%s corpus sha256 = %s, want %s", c.name, got, c.want)
		}
	}
}

var update = flag.Bool("update", false, "rewrite cells.txt from the generator")

// TestPinnedBoard builds every pinned cell, checks it against its spec, and
// compares the cells with cells.txt. A change to the generator or the seed
// shows up as a diff of cells.txt; regenerate it with -update.
func TestPinnedBoard(t *testing.T) {
	var pinned strings.Builder
	fmt.Fprintf(&pinned, "# BenchmarkBoard cells for board.Seed: name, then the sha256 of its\n")
	fmt.Fprintf(&pinned, "# patterns and haystack. Generated by go test -run TestPinnedBoard -update.\n")
	fmt.Fprintf(&pinned, "seed=%#x\n", Seed)
	for _, s := range Cells(Seed) {
		c := s.Build()
		for _, p := range c.Patterns {
			if len(p) < s.LenLo || len(p) > s.LenHi || !utf8.ValidString(p) || isASCII(p) == s.NonASCII {
				t.Fatalf("%s: pattern %q breaks the spec", s.Name(), p)
			}
		}
		if len(c.Patterns) != s.Count || !utf8.ValidString(c.Haystack) ||
			len(c.Haystack) > s.Size || len(c.Haystack) < s.Size-utf8.UTFMax {
			t.Fatalf("%s: %d patterns, %d haystack bytes", s.Name(), len(c.Patterns), len(c.Haystack))
		}
		for _, r := range c.Haystack {
			if r >= utf8.RuneSelf && !slices.Contains(HazardMates(FoldKey(r)), r) {
				t.Fatalf("%s: planted %U, a fold mate outside HazardMates", s.Name(), r)
			}
		}
		if s.Density == "none" && len(Matches(c.Haystack, c.Patterns, s.Sensitive)) != 0 {
			t.Errorf("%s: none-density cell has matches", s.Name())
		}
		digest := sha256.New()
		for _, p := range c.Patterns {
			fmt.Fprintf(digest, "%d:%s", len(p), p)
		}
		digest.Write([]byte(c.Haystack))
		fmt.Fprintf(&pinned, "%s %x\n", s.Name(), digest.Sum(nil))
	}
	if *update {
		if err := os.WriteFile("cells.txt", []byte(pinned.String()), 0o644); err != nil {
			t.Fatal(err)
		}
	}
	if want, err := os.ReadFile("cells.txt"); err != nil || string(want) != pinned.String() {
		t.Fatalf("the generator no longer builds the cells in cells.txt (%v); review, then rerun with -update", err)
	}
}

// naive is a second, slower definition of Matches: compare fold keys rune by
// rune at every rune start.
func naive(haystack string, patterns []string) []Hit {
	var keys, offsets []int
	for i, r := range haystack {
		keys, offsets = append(keys, int(FoldKey(r))), append(offsets, i)
	}
	offsets = append(offsets, len(haystack))
	var hits []Hit
	for i := 0; i < len(keys); i++ {
		for p, pattern := range patterns {
			k := 0
			for _, r := range pattern {
				if i+k >= len(keys) || keys[i+k] != int(FoldKey(r)) {
					k = -1
					break
				}
				k++
			}
			if k > 0 {
				hits = append(hits, Hit{Start: offsets[i], Pattern: p, Width: offsets[i+k] - offsets[i]})
				i += k - 1
				break
			}
		}
	}
	return hits
}

func TestMatchesAgreesWithNaive(t *testing.T) {
	alphabet := []rune("kKKsSſσςΣaAbB ßẞåÅÅµμΜжЖоᲂ")
	rng := rand.New(rand.NewPCG(1, 2))
	random := func(n int) string {
		var b strings.Builder
		for range n {
			b.WriteRune(alphabet[rng.IntN(len(alphabet))])
		}
		return b.String()
	}
	for iteration := range 5000 {
		haystack := random(rng.IntN(40))
		patterns := make([]string, 1+rng.IntN(4))
		for i := range patterns {
			patterns[i] = random(1 + rng.IntN(3))
		}
		if got, want := Matches(haystack, patterns, false), naive(haystack, patterns); !slices.Equal(got, want) {
			t.Fatalf("iteration %d: Matches(%q, %q) = %v, naive %v", iteration, haystack, patterns, got, want)
		}
	}
	if got := Matches("aAa", []string{"a"}, true); len(got) != 2 || got[1].Start != 2 {
		t.Fatalf("case-sensitive Matches = %v", got)
	}
}
